export enum LimitOrderStatus {
    Unknown = 'Unknown',
    MessageProcessingDisabled = 'MessageProcessingDisabled',
    Ok = 'Ok',
    LowBalance = 'LowBalance',
    DisabledAsset = 'DisabledAsset',
    UnknownAsset = 'UnknownAsset',
    Duplicate = 'Duplicate',
    BadRequest = 'BadRequest',
    Runtime = 'Runtime',
    Replaced = 'Replaced',
    NotFoundPrevious = 'NotFoundPrevious',
    ReservedVolumeHigherThanBalance = 'ReservedVolumeHigherThanBalance',
    LimitOrderNotFound = 'LimitOrderNotFound',
    BalanceLowerThanReserved = 'BalanceLowerThanReserved',
    LeadToNegativeSpread = 'LeadToNegativeSpread',
    TooSmallVolume = 'TooSmallVolume',
    InvalidFee = 'InvalidFee',
    InvalidPrice = 'InvalidPrice',
    NoLiquidity = 'NoLiquidity',
    NotEnoughFunds = 'NotEnoughFunds',
    InvalidVolumeAccuracy = 'InvalidVolumeAccuracy',
    InvalidPriceAccuracy = 'InvalidPriceAccuracy',
    InvalidVolume = 'InvalidVolume',
    TooHighPriceDeviation = 'TooHighPriceDeviation',
    InvalidOrderValue = 'InvalidOrderValue',
    NegativeOverdraftLimit = 'NegativeOverdraftLimit'
}